### ISSUE TITLE
Cast Youtube Media

### ISSUE THREAD

**Issue by Rafazeon** [react-native-google-cast/react-native-google-cast#111]
How can I stream a video from youtube to my chromecast?

**Comment by petrbela** [comment]
I assume you have an app from which you want to cast a video that's hosted on YouTube. In order to do that, you first need to obtain a URL of the video stream.

If it's your own video then I think YouTube gives you a URL in the Creator Studio (or however it's called).

If it's not your own video, then you'd need to parse YouTube. Unfortunately, that goes beyond the scope of this library, and youtube-dl, a popular library for doing so, has recently had some issues with copyright, so please make sure you're not doing anything illegal ;)
