### ISSUE TITLE
How to do Slideshow in Chromecast 

### ISSUE THREAD

**Issue by rangav** [react-native-google-cast/react-native-google-cast#116]
Any suggestions how best to implement slideshow feature.
To cast multiple images and change each pic after 5 seconds.?

**Comment by petrbela** [comment]
Hi! This is going to be possible in v4. I'll add examples of how to do it.

**Comment by Purvik** [comment]
@petrbela  Hey, looking for the same thing. Have you done any example for it?
Please share the details of it.

**Comment by rangav** [comment]
Hi @petrbela any update on slideshow.

**Comment by rangav** [comment]
Hi @petrbela any suggestions on this?

**Comment by petrbela** [comment]
The default/styled receivers only support autoplay for audios and videos. You can either create a custom receiver, or change the photo on an interval, for example:

```js
function MyComponent() {
  const client = useRemoteMediaClient()

  useEffect(() => {
    if (!client) return

    client.loadMedia({ queueData: { items: [...] }})

    const interval = setInterval(() => {
      client?.queueNext().catch(() => clearInterval(interval))
    }, 5000)

    return () => clearInterval(interval)
  }, [client])

  // ...
}
```

**Comment by user-o712345** [comment]
Hi @rangav @Purvik!

Sorry for pulling you in out of the blue. I also want to cast a slideshow, but with an audio. [By separating the `castButton` from `loadMedia` method and cast initiation](https://github.com/react-native-google-cast/react-native-google-cast/issues/483#issuecomment-2483603288), I could cast a single item, but getting 2103 error for queues. 


As in the data logs below, `useMediaStatus` or `getMediaStatus` returns empty array for `queueItems`. Thus, methods like `queueNext` wouldn't work. My guess is that it's probably due to the client being {}. 

**_Question:_** Where you able to cast slideshow queue properly (ie. non-empty `queueItems` array)? Would you mind sharing some insights?


**Data logs**
```
castSession: 
{"client": {}, 
"id": "536e923e-798a-4532-883e-ef42f8da3cb3"}

useMediaStatus: 
{"currentItemId": 1, 
"currentQueueItem": null, 
"customData": null, 
"idleReason": null, 
"isMuted": false, 
"mediaInfo": {
    "contentId": "someID", 
    "contentType": null, 
    "contentUrl": "someUrl", 
    "customData": null, 
    "entity": null, 
    "hlsSegmentFormat": null, 
    "hlsVideoSegmentFormat": null, 
    "mediaTracks": [], 
    "metadata": {"artist": null, 
    "images": [Array], 
    "releaseDate": null, 
    "subtitle": null, 
    "title": "someTitle", 
    "type": "generic"}, 
    "streamDuration": 3027, 
    "streamType": "none", 
    "textTrackStyle": null
}, 
"playbackRate": 1, 
"playerState": null, 
"queueItems": [],  <- shouldn't this reflect the media that I loaded initially?
"queueRepeatMode": "off", 
"streamPosition": 0, 
"videoInfo": null, 
"volume": 1}
```
