### ISSUE TITLE
Unable to discover in iOS 13.1.2

### ISSUE THREAD

**Issue by lindborg** [react-native-google-cast/react-native-google-cast#148]
I had a working app, and after updating to iOS 13.1.2 I can't discover nearby devices. It still works if I run it in my Simulator from Xcode on the same network. I can also discover "nearby device" if I get really close to a chromecast (probably through bluetooth), but it won't automatically list and name the devices as previously. 

Any suggestions to solving this issue?

**Comment by nenjamin2405** [comment]
@lindborg I'm facing the same problem, the previous app worked, but now it didn't. @petrbela please help us on this

**Comment by nenjamin2405** [comment]
Hi @lindborg, did you have a solution for this issue?

**Comment by nbennink** [comment]
What version of the SDK are you using? iOS13 changed a few things that's why Google recommends to update to version 4.4.4.

> Some system-level APIs relating to device discovery will change behaviors in iOS 13, and we will update the Google Cast SDK accordingly. We strongly recommend that you update your apps to the new SDK <mentioned to be 4.4.4> to avoid a degraded experience on iOS 13.

There are a few issues with this library and SDK versions newer than V4.3 (#134). I'm still finding a "good" solution for this. The dynamic framework appears to work but the downside is that you are unable to install it using Pods.

**Comment by nenjamin2405** [comment]
Hi @nbennink, I had the same duplicate symbols issue like the above link. But because of the lack of skills and knowledge related to dynamic framework linking, I still cannot make it work, so could you please help me to confirm and answer questions of dynamic framework method below, I'll really appreciate:
1. I need to follow the `Manual Setup` section in this [link](https://developers.google.com/cast/docs/ios_sender)to config the dynamic framework right?
2. On this step, which one should be the one to be chosen? Is it `Dynamic With Guest Mode`?
![image](https://user-images.githubusercontent.com/16648769/67384725-e7504e00-f5bb-11e9-9c5d-3910444d7e40.png)
3. Do I need to remove the line `pod 'google-cast-sdk', '~> 4'` in Podfile? If yes, what is the best way to remove it from Pods?
4. Do I need to remove the below code snippet in AppDelegate.m?
![image](https://user-images.githubusercontent.com/16648769/67384970-58900100-f5bc-11e9-9c12-9b3d59278417.png)
5. After above steps, is there any missing step? Because I got the error said that `it cannot find the GoogleCast instance when I build the app`

Thank you so much

**Comment by petrbela** [comment]
It looks like the `google-cast-sdk-no-bluetooth` pod compiles successfully. I'm still testing for any side-effects but will probably end up changing the dependency in podspec and releasing a new version.

@nbennink Did you manage to get the library work with the Manual Setup? Could you please provide any details? I'll then update the README instructions.

**Comment by lindborg** [comment]
Really appreciate the work @petrbela. Do you know when we can expect a new version?

**Comment by petrbela** [comment]
Ok deployed. Can you guys test 3.2.0? In Podfile use `pod react-native-google-cast/NoBluetooth'`

**Comment by nenjamin2405** [comment]
Awesome @petrbela!!!, It works now with `pod 'react-native-google-cast/NoBluetooth'` option, really appreciate your work on the new version. However, when I tried to use this option to leverage the bluetooth:

  ```
  pod 'react-native-google-cast', path: '../node_modules/react-native-google-cast/ios/'
  pod 'google-cast-sdk', '4.3.0'
  ```

when the popup `Connect to nearby device` appears, it is not touchable, I couldn't choose any option of `Connect`, `Skip`, or `Cancel`. Do you have any idea what this problem is?

**Comment by petrbela** [comment]
@nenjamin2405 My hunch would be something to do with the older version of the SDK and iOS 13. If it only appears on 4.3.0, I probably won't have the capacity to test this and will instead focus on supporting the latest version now that it works without Bluetooth (I also want to look into using the Manual installation option with Bluetooth). Feel free to investigate yourself and please report back your findings :)

**Comment by gavrichards** [comment]
Just wanted to say thanks for the great work here, I've been able to get this working in my new app now. Looking forward to further updates :)
