### ISSUE TITLE
iOS cast local file

### ISSUE THREAD

**Issue by MaxDesplanches** [react-native-google-cast/react-native-google-cast#159]
Hello there,

Your package works like a charme on iOS, but I am trying to cast not from an url, but from local.

I am using package "react-native-image-crop-picker" to select media, but path url does not seems to be supported:

The app connect to chromecast, the icon stay blue on screen but mobile does nothing.

Here is the local url I have tried (big bunny works well with https protocol):

"file:///var/mobile/Media/PhotoData/CPLAssets/group43/A7E1E79D-57AA-4FA2-B8F9-30A1912DFD98.MP4"
or 
"file:///private/var/mobile/Containers/Data/Application/81B8388C-8A1B-4D8C-8F9D-46F48AE7F5BD/tmp/react-native-image-crop-picker/1B5B8A29-14AA-4C20-95B4-1AE3CC8AEC74.mp4"

Do you have any idea ? Did I miss permission to set in Xcode ?

Thanks you in advance

**Comment by MaxDesplanches** [comment]
It is not possible after reading documentation, the cast protocol only allow distance media, except if I share the screen stream.

**Comment by petrbela** [comment]
I haven't tried it myself but the Cast receiver is effectively a Chrome browser that downloads and plays remote media, so you'll need to give it a remote URL to a file on your iOS device (`file:` protocol won't work because that would point to a local file on the Chromecast device, not your phone). I believe the way the "LocalCast" apps that you can find on App Store that enable you to cast local files do this is run a local HTTP server on the mobile device, and then pass a URL to a file on that local server.

**Comment by lcevasco-antorcha** [comment]
Using react-native-static-server may work.

**Comment by petrbela** [comment]
Closing as it's outside the scope of this library.
