### ISSUE TITLE
MediaStatus properties undefined in listener and useEffect [iOS]

### ISSUE THREAD

**Issue by maliotti** [react-native-google-cast/react-native-google-cast#258]
**Describe the bug**
On iOS, the `MediaStatus` properties are `undefined` when setting up a listener on the client for `onMediaStatusUpdated` as well as setting up a `useEffect` on the media status.

**Versions:**
- RNGC Library Version: 4.0.0-beta.6

**To Reproduce**
1. Set up an `onMediaStatusUpdated` listener on the `client` and/or set up a `useEffect(() => {...}, [mediaStatus]);`
2. `console.log(mediaStatus.playerState)` and `console.log(mediaStatus.streamPosition)`, etc.
3. Notice that the values are `undefined`
4. Trying the above three steps on Android will return properties that are **not** undefined

**Expected behavior**
The values for the `MediaStatus` properties should be accessible. The only way I found to get at the properties was to set up a `useEffect` on the media status and then call `getMediaStatus` on the client.

**Comment by FrenchBully** [comment]
I'm seeing the same on all hooks..not sure what happened but beta5 was returning the correct events.

**Comment by petrbela** [comment]
There's a bug in beta.6 (and before) which returns the media status under a nested `mediaStatus` on iOS. A quick fix is to use

```js
let mediaStatus = useMediaStatus()
if (Platform.OS === 'ios') mediaStatus = mediaStatus.mediaStatus
```

It will be fixed in the next release.

As for the difference between beta5, I think I might've changed the format of values returned from events to be consistent with the documentation.

If there's a specific inconsistency between beta6 and the current documentation (other than the mediaStatus event), could you please post it here so I can fix it?

**Comment by petrbela** [comment]
This should be fixed now. Please reopen if you still see any issues.
