### ISSUE TITLE
Ignore Cast library without crashing

### ISSUE THREAD

**Issue by maliotti** [react-native-google-cast/react-native-google-cast#287]
We are using this library in our app and it is a great library! However, our app needs to be distributed on the Amazon App Store as well, so our app crashes because (to my knowledge) you can't run Google Play Services on a Kindle (or other Amazon devices). Any chance there will be a release that handles this situation gracefully without crashing the app?

![Screen Shot 2021-02-04 at 2 22 29 PM](https://user-images.githubusercontent.com/5532759/106962968-bd5d6500-66f4-11eb-964f-c08e48b50e9c.png)

**Comment by petrbela** [comment]
Yes it's on my todo list.

**Comment by maliotti** [comment]
@petrbela Awesome! Will it be part of the next release? If so, when do you think it might be available?

**Comment by EyMaddis** [comment]
Any update on this? :) This can also happen on Android TV

**Comment by praveens96** [comment]
none of these solutions worked for me. So, atlast removed/commented the cast code and to not to disturb other code parts, 
- Removed all cast & context related code from native code - MainApplication.java, MainActivity.java, app/build.gradle, build.gradle, settings.gradle
- instead of importing directly from lib react-native-google-cast, imported  from single file in all the places. in this file I am just importing and exporting required hooks, variables.
- in that file, for china release used the below
- `const MediaPlayerState = {};
const CastState = {
    NO_DEVICES_AVAILABLE: 'noDevicesAvailable',
    NOT_CONNECTED: 'notConnected',
    CONNECTING: 'connecting',
    CONNECTED: 'connected',
};
const useMediaStatus = () => {};
const useRemoteMediaClient = () => {};
const useStreamPosition = () => {};
const useCastState = () => {};
const useCastSession = () => {};
export { MediaPlayerState, useMediaStatus, useRemoteMediaClient, useStreamPosition, useCastState, useCastSession, CastState };`

Any other solutions are welcomed.

**Comment by sugajski** [comment]
@petrbela Hi, did you think about when you will focus on this problem?
I'm expanding my app for Huawei App Gallery. v4 of react-native-google-cast crashes all huawei devices. I tried to workaround this problem for days, but didn't handle it.

Appreciate your work! Cheers!

**Comment by EyMaddis** [comment]
See [my comment](https://github.com/react-native-google-cast/react-native-google-cast/issues/287#issuecomment-779280700) above, you have to make sure that React Natives Autolinking is disabled for this package and only initialize for devices that have play services installed/are not Huawei (the check is up to you).
Same goes for Js Components.

**Comment by Nikooos** [comment]
Any change #367 will be merged anytime soon?

**Comment by bberak** [comment]
Hey @EyMaddis,

Thanks for posting your solution 🙏. In your code snippet you use a function called `isFireOS` - would you be able to post the contents of this function? Struggling to find a concrete example of detected FireOS..
