### ISSUE TITLE
DRM support

### ISSUE THREAD

**Issue by zhulduz** [react-native-google-cast/react-native-google-cast#311]
Hi team, 
firstly, thanks for the lib)

Can you please tell is there a DRM support from default receiver? I couldn't find receiver's source code here.

Thanks in advance)

**Comment by zhulduz** [comment]
@petrbela

**Comment by petrbela** [comment]
This library provides RN wrapper for the sender, not the receiver. From [Google Cast's documentation](https://developers.google.com/cast/docs/web_receiver):

> If your app provides content such as an image gallery, requires DRM, or custom business logic, then you need to build a custom Web Receiver application

There's another section in the custom web receiver docs that deals with DRM: https://developers.google.com/cast/docs/web_receiver/streaming_protocols#drm

I don't unfortunately use DRM so I haven't looked into it. From what I can see, it looks like it's entirely handled by the receiver. If you find anything that would need to be changed in the sender (and thus this library), please post a related link.

**Comment by zhulduz** [comment]
@petrbela, thanks for the answer.
Yes, I know that this library for the sender only 😄 

This library uses some receiver with `APP_ID = CC1AD845`, so I am curious is there receiver in open source, where we can see implementation for it?

**Comment by petrbela** [comment]
`CC1AD845` is the default receiver. I'm not aware of an open-source example; in that sense, Google is your friend just as mine. You can also create a custom receiver yourself (it's really simple!), which is what you'll need to do anyway because you need to link your custom receiver to your licensing server in order to make DRM work. I'd recommend looking at the documentation linked above.

I'm closing this issue as it's outside the scope of this library, unless proven otherwise :)
