### ISSUE TITLE
iOS: Title bar is transparent

### ISSUE THREAD

**Issue by gavrichards** [react-native-google-cast/react-native-google-cast#364]
I suspect this started happening since updating to iOS 15.

![IMG_3037](https://user-images.githubusercontent.com/432315/135490398-6d7a13d0-fc50-4246-8284-d8556a0c1c89.jpg)

**Comment by geroale** [comment]
Same issue here

**Comment by petrbela** [comment]
This has been reported to the Google Cast team https://issuetracker.google.com/issues/201085359

I'm closing the issue here as it's not a bug in this library. If you need a workaround please see the link above or answers at https://stackoverflow.com/questions/69111478/ios-15-navigation-bar-transparent. If you do so, feel free to create a PR for the time being; I just won't have time to fix it myself (at least not before hopefully Google fixes it since it affects everyone).

**Comment by gavrichards** [comment]
Thanks @petrbela, I'll hang on for the Google fix.

**Comment by gavrichards** [comment]
@petrbela Google have marked that issue as fixed and say it's in version 4.7.0 of the SDK. Could this library possibly now be updated please?

**Comment by petrbela** [comment]
@gavrichards I don't think there's any specific version required by this library so you should be able to update the native SDK using `pod update`.

**Comment by gavrichards** [comment]
Oh ok, great. I'll give that a try. Thanks.

**Comment by gavrichards** [comment]
To confirm and for anyone else's benefit too - yes this library doesn't require any changes. The key is to update your Podfile to use iOS 12 because that's required by Google Cast SDK 4.7.0.
