### ISSUE TITLE
latest pull but having issues with Android Device.

### ISSUE THREAD

**Issue by fraubungle** [react-native-google-cast/react-native-google-cast#398]
Hi Last week I had an "issue" with the Cast button not showing on the Android Emulator but it was showing on the IOS Simulator and you let me know that this was a known issue. I have now managed with some fighting to get a really simple example build up on to EAS for both Android and IOS but again the Android Version does not have the cast button but the IOS version does. This version is running on device.

I can send you a link for the EAS build if you want.

_Originally posted by @fraubungle in https://github.com/react-native-google-cast/react-native-google-cast/issues/395#issuecomment-1061129947_

**Comment by fraubungle** [comment]
Hi,

is it possible to let me know if there is an issue or if I am doing something wrong on cast button not working on an Android device via EAS build?

**Comment by petrbela** [comment]
I just created a fresh Expo project, added the library (https://github.com/expo/config-plugins/tree/main/packages/react-native-google-cast), ran `eas build -p android --profile preview` (https://docs.expo.dev/build/setup/ -> https://docs.expo.dev/build-reference/apk/), downloaded the apk, and the Cast button shows up. So *in general*, it works but there might be something off in your setup. One thing to note, you should set `tintColor` to `CastButton` style, otherwise it's transparent. I've just updated the docs, let me know if that solves it.

**Comment by petrbela** [comment]
See https://github.com/react-native-google-cast/RNGCExpo for an example of how to use this library with Expo.
