### ISSUE TITLE
GetDevices() method returns the empty device list

### ISSUE THREAD

**Issue by samuel-ferreira-dotcodingbr** [react-native-google-cast/react-native-google-cast#401]
Version Lib: "react-native-google-cast": "^4.2.4"

GetDevices() method returns the empty device list;

My TV device is on and it has LG webOS for streaming videos;

**Comment by petrbela** [comment]
I think LG webOS is not a proper Chromecast device. Based on https://www.reddit.com/r/OLED/comments/jexy15/lg_oled_webos_chromecast_functionality/, you might be able to cast to it from YouTube because they use a custom protocol and the TV has the YouTube app installed.

You might double-check using the official Google Cast example app for [Android](https://github.com/googlecast/CastVideos-android) or [iOS](https://github.com/googlecast/CastVideos-ios) but if it doesn't work there, it won't work in React Native either.
