### ISSUE TITLE
React Native For Roku Cast

### ISSUE THREAD

**Issue by rangav** [react-native-google-cast/react-native-google-cast#95]
Thanks for creating react native library for Chromecast. 

I know this is not relevant here, but interested to know if you any created or used react native for Roku to achieve similar functionality as this library.

I am looking for react native library for Roku, but could not find one.

**Comment by petrbela** [comment]
Hi!

The only option I know of is the [You.i Engine](https://www.youi.tv/youi-engine/react-native/), however, their licensing is quite pricey (we were quoted $50k per platform).

I did some research myself into whether it would be feasible to build a bridge; my conclusion is it would be quite a complex endeavor:

1. Since Roku doesn't provide JavaScript runtime out of the box, you'd need to be able to package a JavaScript engine with your app (RN Android does that too). However, in order to do that, you'd need to be able to build apps in native code (C++). From my understanding, that used to be possible (and still available to some large partners) but the latest Roku SDK only allows you to build apps with BrightScript. The other option would be to cross-compile JavaScript to BrightScript but then you'd essentially need to rebuild all React Native tools to support this new runtime.

2. On top of that, you'd need to recreate RN's layout engine (Yoga).

3. Then, finally, you'd need to bridge all the components/APIs.

4. After all of this is done, I'm still not sure how fast it would be. Adding the extra JavaScript runtime would certainly hurt performance, and it's possible you'd need to take extra care to make it more efficient.

All in all, I probably wouldn't expect an indie developer to come with RN for Roku anytime soon. The reason You.i were able to do this is because they've already done most of the heavy lifting in their native cross-platform engine, and Roku is just another runtime platform for them.

I'll close the issue but feel free to continue the discussion if you find any relevant tools.
